
var BrunsliCodecModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(BrunsliCodecModule) {
  BrunsliCodecModule = BrunsliCodecModule || {};


var b;b||(b=typeof BrunsliCodecModule !== 'undefined' ? BrunsliCodecModule : {});var aa,ba;b.ready=new Promise(function(a,d){aa=a;ba=d});var l={},r;for(r in b)b.hasOwnProperty(r)&&(l[r]=b[r]);var t="./this.program";function u(a,d){throw d;}var v=!1,w=!1,x=!1,ca=!1;v="object"===typeof window;w="function"===typeof importScripts;x="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!v&&!x&&!w;var y="",B,C,E,F;
if(x)y=w?require("path").dirname(y)+"/":__dirname+"/",B=function(a,d){E||(E=require("fs"));F||(F=require("path"));a=F.normalize(a);return E.readFileSync(a,d?null:"utf8")},C=function(a){a=B(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||G("Assertion failed: undefined");return a},1<process.argv.length&&(t=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",function(a){if(!(a instanceof da))throw a;}),process.on("unhandledRejection",G),u=function(a){process.exit(a)},
b.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(B=function(a){return read(a)}),C=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");"object"===typeof a||G("Assertion failed: undefined");return a},"function"===typeof quit&&(u=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:
print);else if(v||w)w?y=self.location.href:document.currentScript&&(y=document.currentScript.src),_scriptDir&&(y=_scriptDir),0!==y.indexOf("blob:")?y=y.substr(0,y.lastIndexOf("/")+1):y="",B=function(a){var d=new XMLHttpRequest;d.open("GET",a,!1);d.send(null);return d.responseText},w&&(C=function(a){var d=new XMLHttpRequest;d.open("GET",a,!1);d.responseType="arraybuffer";d.send(null);return new Uint8Array(d.response)});var ea=b.print||console.log.bind(console),H=b.printErr||console.warn.bind(console);
for(r in l)l.hasOwnProperty(r)&&(b[r]=l[r]);l=null;b.thisProgram&&(t=b.thisProgram);b.quit&&(u=b.quit);var I;b.wasmBinary&&(I=b.wasmBinary);var noExitRuntime;b.noExitRuntime&&(noExitRuntime=b.noExitRuntime);"object"!==typeof WebAssembly&&G("no native wasm support detected");var J,fa=new WebAssembly.Table({initial:357,maximum:357,element:"anyfunc"}),K=!1,ha="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function L(a,d,e){var f=d+e;for(e=d;a[e]&&!(e>=f);)++e;if(16<e-d&&a.subarray&&ha)return ha.decode(a.subarray(d,e));for(f="";d<e;){var h=a[d++];if(h&128){var g=a[d++]&63;if(192==(h&224))f+=String.fromCharCode((h&31)<<6|g);else{var n=a[d++]&63;h=224==(h&240)?(h&15)<<12|g<<6|n:(h&7)<<18|g<<12|n<<6|a[d++]&63;65536>h?f+=String.fromCharCode(h):(h-=65536,f+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else f+=String.fromCharCode(h)}return f}var M,N,O,P;
function ia(a){M=a;b.HEAP8=N=new Int8Array(a);b.HEAP16=new Int16Array(a);b.HEAP32=P=new Int32Array(a);b.HEAPU8=O=new Uint8Array(a);b.HEAPU16=new Uint16Array(a);b.HEAPU32=new Uint32Array(a);b.HEAPF32=new Float32Array(a);b.HEAPF64=new Float64Array(a)}var ja=b.INITIAL_MEMORY||16777216;b.wasmMemory?J=b.wasmMemory:J=new WebAssembly.Memory({initial:ja/65536,maximum:32768});J&&(M=J.buffer);ja=M.byteLength;ia(M);P[120480]=5724960;
function Q(a){for(;0<a.length;){var d=a.shift();if("function"==typeof d)d(b);else{var e=d.M;"number"===typeof e?void 0===d.L?b.dynCall_v(e):b.dynCall_vi(e,d.L):e(void 0===d.L?null:d.L)}}}var ka=[],la=[],ma=[],na=[];function oa(){var a=b.preRun.shift();ka.unshift(a)}var R=0,S=null,T=null;b.preloadedImages={};b.preloadedAudios={};function G(a){if(b.onAbort)b.onAbort(a);H(a);K=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}
function pa(a){var d=U;return String.prototype.startsWith?d.startsWith(a):0===d.indexOf(a)}function qa(){return pa("data:application/octet-stream;base64,")}var U="brunslicodec-wasm.wasm";if(!qa()){var ra=U;U=b.locateFile?b.locateFile(ra,y):y+ra}function sa(){try{if(I)return new Uint8Array(I);if(C)return C(U);throw"both async and sync fetching of the wasm failed";}catch(a){G(a)}}
function ta(){return I||!v&&!w||"function"!==typeof fetch||pa("file://")?new Promise(function(a){a(sa())}):fetch(U,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+U+"'";return a.arrayBuffer()}).catch(function(){return sa()})}la.push({M:function(){ua()}});var va={},wa=[null,[],[]],Aa={},Ba={};
function Ca(){if(!Da){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:t||"./this.program"},d;for(d in Ba)a[d]=Ba[d];var e=[];for(d in a)e.push(d+"="+a[d]);Da=e}return Da}var Da;function V(a){return 0===a%4&&(0!==a%100||0===a%400)}function Ea(a,d){for(var e=0,f=0;f<=d;e+=a[f++]);return e}
var W=[31,29,31,30,31,30,31,31,30,31,30,31],X=[31,28,31,30,31,30,31,31,30,31,30,31];function Y(a,d){for(a=new Date(a.getTime());0<d;){var e=a.getMonth(),f=(V(a.getFullYear())?W:X)[e];if(d>f-a.getDate())d-=f-a.getDate()+1,a.setDate(1),11>e?a.setMonth(e+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+d);break}}return a}
function Fa(a,d,e,f){function h(c,k,m){for(c="number"===typeof c?c.toString():c||"";c.length<k;)c=m[0]+c;return c}function g(c,k){return h(c,k,"0")}function n(c,k){function m(xa){return 0>xa?-1:0<xa?1:0}var z;0===(z=m(c.getFullYear()-k.getFullYear()))&&0===(z=m(c.getMonth()-k.getMonth()))&&(z=m(c.getDate()-k.getDate()));return z}function A(c){switch(c.getDay()){case 0:return new Date(c.getFullYear()-1,11,29);case 1:return c;case 2:return new Date(c.getFullYear(),0,3);case 3:return new Date(c.getFullYear(),
0,2);case 4:return new Date(c.getFullYear(),0,1);case 5:return new Date(c.getFullYear()-1,11,31);case 6:return new Date(c.getFullYear()-1,11,30)}}function D(c){c=Y(new Date(c.F+1900,0,1),c.K);var k=new Date(c.getFullYear()+1,0,4),m=A(new Date(c.getFullYear(),0,4));k=A(k);return 0>=n(m,c)?0>=n(k,c)?c.getFullYear()+1:c.getFullYear():c.getFullYear()-1}var q=P[f+40>>2];f={P:P[f>>2],O:P[f+4>>2],I:P[f+8>>2],H:P[f+12>>2],G:P[f+16>>2],F:P[f+20>>2],J:P[f+24>>2],K:P[f+28>>2],X:P[f+32>>2],N:P[f+36>>2],R:q?q?
L(O,q,void 0):"":""};e=e?L(O,e,void 0):"";q={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in q)e=e.replace(new RegExp(p,"g"),q[p]);var ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
za="January February March April May June July August September October November December".split(" ");q={"%a":function(c){return ya[c.J].substring(0,3)},"%A":function(c){return ya[c.J]},"%b":function(c){return za[c.G].substring(0,3)},"%B":function(c){return za[c.G]},"%C":function(c){return g((c.F+1900)/100|0,2)},"%d":function(c){return g(c.H,2)},"%e":function(c){return h(c.H,2," ")},"%g":function(c){return D(c).toString().substring(2)},"%G":function(c){return D(c)},"%H":function(c){return g(c.I,2)},
"%I":function(c){c=c.I;0==c?c=12:12<c&&(c-=12);return g(c,2)},"%j":function(c){return g(c.H+Ea(V(c.F+1900)?W:X,c.G-1),3)},"%m":function(c){return g(c.G+1,2)},"%M":function(c){return g(c.O,2)},"%n":function(){return"\n"},"%p":function(c){return 0<=c.I&&12>c.I?"AM":"PM"},"%S":function(c){return g(c.P,2)},"%t":function(){return"\t"},"%u":function(c){return c.J||7},"%U":function(c){var k=new Date(c.F+1900,0,1),m=0===k.getDay()?k:Y(k,7-k.getDay());c=new Date(c.F+1900,c.G,c.H);return 0>n(m,c)?g(Math.ceil((31-
m.getDate()+(Ea(V(c.getFullYear())?W:X,c.getMonth()-1)-31)+c.getDate())/7),2):0===n(m,k)?"01":"00"},"%V":function(c){var k=new Date(c.F+1901,0,4),m=A(new Date(c.F+1900,0,4));k=A(k);var z=Y(new Date(c.F+1900,0,1),c.K);return 0>n(z,m)?"53":0>=n(k,z)?"01":g(Math.ceil((m.getFullYear()<c.F+1900?c.K+32-m.getDate():c.K+1-m.getDate())/7),2)},"%w":function(c){return c.J},"%W":function(c){var k=new Date(c.F,0,1),m=1===k.getDay()?k:Y(k,0===k.getDay()?1:7-k.getDay()+1);c=new Date(c.F+1900,c.G,c.H);return 0>n(m,
c)?g(Math.ceil((31-m.getDate()+(Ea(V(c.getFullYear())?W:X,c.getMonth()-1)-31)+c.getDate())/7),2):0===n(m,k)?"01":"00"},"%y":function(c){return(c.F+1900).toString().substring(2)},"%Y":function(c){return c.F+1900},"%z":function(c){c=c.N;var k=0<=c;c=Math.abs(c)/60;return(k?"+":"-")+String("0000"+(c/60*100+c%60)).slice(-4)},"%Z":function(c){return c.R},"%%":function(){return"%"}};for(p in q)0<=e.indexOf(p)&&(e=e.replace(new RegExp(p,"g"),q[p](f)));p=Ga(e);if(p.length>d)return 0;N.set(p,a);return p.length-
1}
function Ga(a){for(var d=0,e=0;e<a.length;++e){var f=a.charCodeAt(e);55296<=f&&57343>=f&&(f=65536+((f&1023)<<10)|a.charCodeAt(++e)&1023);127>=f?++d:d=2047>=f?d+2:65535>=f?d+3:d+4}d=Array(d+1);f=d.length;e=0;if(0<f){f=e+f-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var n=a.charCodeAt(++h);g=65536+((g&1023)<<10)|n&1023}if(127>=g){if(e>=f)break;d[e++]=g}else{if(2047>=g){if(e+1>=f)break;d[e++]=192|g>>6}else{if(65535>=g){if(e+2>=f)break;d[e++]=224|g>>12}else{if(e+3>=f)break;d[e++]=
240|g>>18;d[e++]=128|g>>12&63}d[e++]=128|g>>6&63}d[e++]=128|g&63}}d[e]=0}return d}
var Ja={g:function(){P[Ha()>>2]=63;return-1},f:function(a,d){if(-1===(a|0)||0===d)a=-28;else{var e=va[a];e&&d===e.V&&(va[a]=null,e.S&&Ia(e.W));a=0}return a},a:function(){G()},m:function(a,d,e){O.copyWithin(a,d,d+e)},b:function(a){a>>>=0;var d=O.length;if(2147483648<a)return!1;for(var e=1;4>=e;e*=2){var f=d*(1+.2/e);f=Math.min(f,a+100663296);f=Math.max(16777216,a,f);0<f%65536&&(f+=65536-f%65536);a:{try{J.grow(Math.min(2147483648,f)-M.byteLength+65535>>>16);ia(J.buffer);var h=1;break a}catch(g){}h=
void 0}if(h)return!0}return!1},h:function(a,d){var e=0;Ca().forEach(function(f,h){var g=d+e;h=P[a+4*h>>2]=g;for(g=0;g<f.length;++g)N[h++>>0]=f.charCodeAt(g);N[h>>0]=0;e+=f.length+1});return 0},i:function(a,d){var e=Ca();P[a>>2]=e.length;var f=0;e.forEach(function(h){f+=h.length+1});P[d>>2]=f;return 0},c:function(a){if(!noExitRuntime&&(K=!0,b.onExit))b.onExit(a);u(a,new da(a))},k:function(){return 0},j:function(a,d,e,f){a=Aa.U(a);d=Aa.T(a,d,e);P[f>>2]=d;return 0},l:function(){},d:function(a,d,e,f){for(var h=
0,g=0;g<e;g++){for(var n=P[d+8*g>>2],A=P[d+(8*g+4)>>2],D=0;D<A;D++){var q=O[n+D],p=wa[a];0===q||10===q?((1===a?ea:H)(L(p,0)),p.length=0):p.push(q)}h+=A}P[f>>2]=h;return 0},memory:J,e:function(a,d,e,f){return Fa(a,d,e,f)},table:fa};
(function(){function a(h){b.asm=h.exports;R--;b.monitorRunDependencies&&b.monitorRunDependencies(R);0==R&&(null!==S&&(clearInterval(S),S=null),T&&(h=T,T=null,h()))}function d(h){a(h.instance)}function e(h){return ta().then(function(g){return WebAssembly.instantiate(g,f)}).then(h,function(g){H("failed to asynchronously prepare wasm: "+g);G(g)})}var f={a:Ja};R++;b.monitorRunDependencies&&b.monitorRunDependencies(R);if(b.instantiateWasm)try{return b.instantiateWasm(f,a)}catch(h){return H("Module.instantiateWasm callback failed with error: "+
h),!1}(function(){if(I||"function"!==typeof WebAssembly.instantiateStreaming||qa()||pa("file://")||"function"!==typeof fetch)return e(d);fetch(U,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,f).then(d,function(g){H("wasm streaming compile failed: "+g);H("falling back to ArrayBuffer instantiation");return e(d)})})})();return{}})();var ua=b.___wasm_call_ctors=function(){return(ua=b.___wasm_call_ctors=b.asm.n).apply(null,arguments)};
b._BrunsliToJpeg=function(){return(b._BrunsliToJpeg=b.asm.o).apply(null,arguments)};b._BrunsliDecoderInit=function(){return(b._BrunsliDecoderInit=b.asm.p).apply(null,arguments)};b._malloc=function(){return(b._malloc=b.asm.q).apply(null,arguments)};b._BrunsliDecoderProcess=function(){return(b._BrunsliDecoderProcess=b.asm.r).apply(null,arguments)};b._BrunsliDecoderCleanup=function(){return(b._BrunsliDecoderCleanup=b.asm.s).apply(null,arguments)};
b._GetJpegData=function(){return(b._GetJpegData=b.asm.t).apply(null,arguments)};b._GetJpegLength=function(){return(b._GetJpegLength=b.asm.u).apply(null,arguments)};b._FreeJpeg=function(){return(b._FreeJpeg=b.asm.v).apply(null,arguments)};b._JpegToBrunsli=function(){return(b._JpegToBrunsli=b.asm.w).apply(null,arguments)};b._GetBrunsliData=function(){return(b._GetBrunsliData=b.asm.x).apply(null,arguments)};b._GetBrunsliLength=function(){return(b._GetBrunsliLength=b.asm.y).apply(null,arguments)};
b._FreeBrunsli=function(){return(b._FreeBrunsli=b.asm.z).apply(null,arguments)};var Ia=b._free=function(){return(Ia=b._free=b.asm.A).apply(null,arguments)},Ha=b.___errno_location=function(){return(Ha=b.___errno_location=b.asm.B).apply(null,arguments)};b.dynCall_vi=function(){return(b.dynCall_vi=b.asm.C).apply(null,arguments)};b.dynCall_v=function(){return(b.dynCall_v=b.asm.D).apply(null,arguments)};var Z;
function da(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}T=function Ka(){Z||La();Z||(T=Ka)};
function La(){function a(){if(!Z&&(Z=!0,b.calledRun=!0,!K)){Q(la);Q(ma);aa(b);if(b.onRuntimeInitialized)b.onRuntimeInitialized();if(b.postRun)for("function"==typeof b.postRun&&(b.postRun=[b.postRun]);b.postRun.length;){var d=b.postRun.shift();na.unshift(d)}Q(na)}}if(!(0<R)){if(b.preRun)for("function"==typeof b.preRun&&(b.preRun=[b.preRun]);b.preRun.length;)oa();Q(ka);0<R||(b.setStatus?(b.setStatus("Running..."),setTimeout(function(){setTimeout(function(){b.setStatus("")},1);a()},1)):a())}}b.run=La;
if(b.preInit)for("function"==typeof b.preInit&&(b.preInit=[b.preInit]);0<b.preInit.length;)b.preInit.pop()();noExitRuntime=!0;La();


  return BrunsliCodecModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = BrunsliCodecModule;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return BrunsliCodecModule; });
    else if (typeof exports === 'object')
      exports["BrunsliCodecModule"] = BrunsliCodecModule;
    