name: CMake WASM build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        include:
        - os: ubuntu
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache EMSDK
      id: cache-emsdk
      uses: actions/cache@v1
      with:
        path: ~/emsdk
        key: ${{ runner.os }}-emsdk

    - name: install
      if: steps.cache-emsdk.outputs.cache-hit != 'true'
      run: |
        cd ~/
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest

    - name: post-install
      run: |
        cd ~/emsdk
        ./emsdk activate latest

    - name: configure
      run: >-
        source ~/emsdk/emsdk_env.sh &&
        cmake
        -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake"
        -DCMAKE_BUILD_TYPE=Release
        -B out

    - name: build
      run: cmake --build out --config Release -j 2

    - name: test
      run: cd out && ctest -j 2
