# Copyright (c) the JPEG XL Project Authors. All rights reserved.
#
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Workflow to run pull-requests specific checks.

name: PR
on:
  merge_group:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'CI:none') }}
    runs-on: [ubuntu-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
      with:
        egress-policy: audit

    - name: Checkout the source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Install tools
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install buildifier typos-cli zizmor

    - name: lint
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        # Used for creating empty git tree.
        git config user.email "robot@example.com"
        git config user.name "Robot"
        CLANG_PATCH=./clang-format.patch ./scripts/lint.sh lint >&2

    # For developers who don't want to install clang-format.
    # TODO(eustas): also upload patch for buildifier
    - name: upload patch
      if: failure()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: clang-format.patch
        path: ./clang-format.patch
        archive: false


